# Generated by Django 3.0.8 on 2020-09-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_decode', models.CharField(max_length=200)),
                ('decoded_text', models.CharField(editable=False, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Encoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_encode', models.CharField(max_length=200)),
                ('encoded_text', models.CharField(editable=False, max_length=200)),
            ],
        ),
    ]
